<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 24/4/20
 * Time: 1:26 AM
 */

namespace App\Repositories;

use App\Models\User;
use App\Models\Comment;
use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Illuminate\Support\Facades\Hash;
use Luezoid\Laravelcore\Services\EnvironmentService;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class CommentRepository extends EloquentBaseRepository
{
    public $model = Comment::class;

    public function create($data)
    {
        try {
            $data["data"]["user_id"] = EnvironmentService::getLoggedInUserId();
        } catch (\Exception $e) {
        }
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update($data)
    {
        $loggedUser=EnvironmentService::getLoggedInUserId();
        $commentUser = Comment::where('id',$data['id'])->value('user_id');

        if($commentUser == $loggedUser) {
            return parent::update($data); // TODO: Change the autogenerated stub
        }else{
            throw new NotFoundHttpException();
        }


    }

    public function delete($data)
    {
        $loggedUser=EnvironmentService::getLoggedInUserId();
        $commentUser = Comment::where('id',$data['id'])->value('user_id');

        if($commentUser == $loggedUser) {
            return parent::delete($data);
        }else{
            throw new NotFoundHttpException();
        }
    }

}
