<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 24/4/20
 * Time: 1:26 AM
 */

namespace App\Repositories;

use App\Models\User;
use App\Models\Comment;
use Illuminate\Auth\AuthenticationException;
use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Illuminate\Support\Facades\Hash;
use Luezoid\Laravelcore\Services\EnvironmentService;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class CommentRepository extends EloquentBaseRepository
{
    public $model = Comment::class;

    public function create($data)
    {
        $data["data"]["user_id"] = EnvironmentService::getLoggedInUserId();
        return parent::create($data); // TODO: Change the autogenerated stub
    }


    public function update($data)
    {

        /*For providing authorization before executing the request
         *
         *
        $loggedUser=EnvironmentService::getLoggedInUserId();
        $commentUser = Comment::where('id',$data['id'])->value('user_id');
        if($commentUser) {
            if ($commentUser == $loggedUser) {
                return parent::update($data); //
            } else {
                throw new AuthenticationException();
            }
        } else throw new NotFoundHttpException();
*/
        $this->AuthorizeUser($data,$this->model,'user_id');
        return parent::update($data);
    }

    public function delete($data)
    {
        $this->AuthorizeUser($data,$this->model,'user_id');
        return parent::delete($data);
    }


}
