<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 24/4/20
 * Time: 1:26 AM
 */

namespace App\Repositories;

use App\Models\User;
use App\Models\Comment;
use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Illuminate\Support\Facades\Hash;
class CommentRepository extends EloquentBaseRepository
{
    public $model = Comment::class;

    public function create($data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update($data)
    {
        return parent::update($data); // TODO: Change the autogenerated stub
    }

    public function delete($data)
    {
        return parent::delete($data); // TODO: Change the autogenerated stub
    }

}
