<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 24/4/20
 * Time: 1:26 AM
 */

namespace App\Repositories;

use App\Models\User;
use App\Models\Post;
use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Illuminate\Support\Facades\Hash;
use Luezoid\Laravelcore\Services\EnvironmentService;
class PostRepository extends EloquentBaseRepository
{
    public $model = Post::class;

    public function create($data)
    {
        try {
            $data["data"]["user_id"] = EnvironmentService::getLoggedInUserId();
        } catch (\Exception $e) {
        }
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update($data)
    {
        try {
            $data["data"]["user_id"] = EnvironmentService::getLoggedInUserId();
        } catch (\Exception $e) {
        }
        return parent::update($data); // TODO: Change the autogenerated stub
    }

    public function delete($data)
    {
        return parent::delete($data); // TODO: Change the autogenerated stub
    }

}
