<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 24/4/20
 * Time: 1:26 AM
 */

namespace App\Repositories;

use App\Models\Comment;
use App\Models\User;
use App\Models\Post;
use Cassandra\Exception\AuthenticationException;
use Illuminate\Auth\Access\AuthorizationException;
use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Illuminate\Support\Facades\Hash;
use Luezoid\Laravelcore\Services\EnvironmentService;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Luezoid\Laravelcore\Http\Controllers\ApiController;
class PostRepository extends EloquentBaseRepository
{

    use AuthorizesRequests;
    public $model = Post::class;

    public function create($data)
    {
        $data["data"]["user_id"] = EnvironmentService::getLoggedInUserId();
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update($data)
    {
        $this->AuthorizeUser($data,$this->model,'user_id');
        return parent::update($data);
    }

    public function delete($data)
    {
        $this->AuthorizeUser($data,$this->model,'user_id');
        return parent::delete($data);
    }


}
