<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 24/4/20
 * Time: 1:26 AM
 */

namespace App\Repositories;

use App\Models\User;
use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Illuminate\Support\Facades\Hash;
class UserRepository extends EloquentBaseRepository
{
    public $model = User::class;

    public function create($data)
    {
        $data['data']['password']=Hash::make($data['data']['password']);
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function getAll($params = [], $query = null)
    {
        $params['with']=['posts','comments'];
        return parent::getAll($params, $query); // TODO: Change the autogenerated stub
    }

    public function update($data)
    {
        if(key_exists('password',$data['data'])){
            $data['data']['password'] = Hash::make($data['data']['password']);
        }

        return parent::update($data); // TODO: Change the autogenerated stub
    }

    public function delete($data)
    {
        return parent::delete($data); // TODO: Change the autogenerated stub
    }

}
